name = "Apéro"
license = "CC-BY-4.0"
licenselink = "https://github.com/hugo-apero/hugo-apero/blob/master/LICENSE.md"
description = "A Hugo theme you'll want to hang out with."
homepage = "https://hugo-apero.netlify.app"
tags = ["blog", "personal", "portfolio", "responsive", "customizable"]
features = ["projects", "collections", "CV"]
min_version = "0.79.0"

# If the theme has a single author
[author]
    name = "Vicky Xu"
    homepage = "https://www.linkedin.com/in/vicky-x-b82324251/"

# If porting an existing theme
[original]
    author = "Formspree"
    homepage = "https://blogophonic-hugo.netlify.app/"
    repo = "https://github.com/formspree/blogophonic-hugo"